### ISSUE TITLE
Treefarm is lost when placed in invalid location

### ISSUE THREAD

**Issue by Pandemoneus** [Blu3wolf/Treefarm-Lite#30]
In Treefarm Lite version 0.4.0, when you place a tree farm (MK1) in an invalid location, you no longer get the error message (as in previous versions), instead it just disappears and is lost. You don't get the item back.

**Comment by secondadvent** [comment]
From what I've seen the item isn't lost, it just gets dropped on the ground near where you tried to place it. It also seems to have trouble placing on top of spots with ground clutter like grass and small rock entities that wouldn't normally prevent building anywhere but still have collision boxes (placing and removing bricks over those spots makes them suitable for farms).

**Comment by StephenWard** [comment]
@Pandemoneus if it was placed by the player, and not a robot, then it should go back into player inventory and you should still see the error message - but if it's placed by a robot then there is no message (b/c there is no player to get.. hmm) and the item will be dropped on the ground.

shift-clicking w/ the personal roboport equipped counts as being placed by a robot, btw. Is that what you were doing?

@secondadvent a treefarm mk1 should ignore trees and "decorative" items in its placement box - do you recall any specific entities that prevented placement?

**Comment by Pandemoneus** [comment]
No, I was just trying to place it by hand. However I didn't check whether the item is dropped somewhere on the ground.
[edit]
Ok, it is dropped.

**Comment by secondadvent** [comment]
Actually, trying again it seems like ground clutter -is- ignored, but any tile of the farm hitting any other entity besides the player (even ore), even though shown as "placeable" will cause it to fail and drop on the ground with no message. The only part that actually causes it to display red when trying to place is the chest, though it will not place if any tile of the field is obstructed. Not sure what was blocking my first field I tried to place at the start, since I recall having to place/remove brick to clear stuff to place it, but it may just have overlapped something I didn't see on an edge or something.

You can freely place objects on the field area after it's placed (like conveyor belts, which I use along the right edge when placing multiple fields to save space), but if you pick the farm up and place it in the same spot it will fail and drop.

EDIT: Another issue I've noticed is that they cause massive slowdown (from 60 fps/ups to 15-20 of both with my 30 farms) if they get their output of wood backed up. I recall loading up my save one day and getting massive stuttering and slowdown, which only went away after running to my fields and manually removing the wood - I didn't have a buffer because I wanted the trees to stay grown until needed to help reduce pollution.

After putting in a large buffer I haven't had any trouble, except in the uncommon times where a bunch of trees mature at once and my output can't keep up, then it's just a second or two of stutter. Other than this I haven't had any performance issues with the treefarms going.

**Comment by StephenWard** [comment]
@secondadvent  was the stutter on v4.0? and you had 20 mk1 farms??

**Comment by secondadvent** [comment]
Yeah, I just updated from the pull request version to the actual 4.0 release build and it's still an issue. With my 30 farms intentionally backed up (just to speed up the process) I'm currently dropping from my normal 60 to around 40 fps/ups, though the fields just harvested a bunch of the trees so there's not as many mature ones as the last time they backed up. As more trees mature my speed continues to drop, and as soon as I clear all of the wood from the inventories, even with the belts still backed up, the speed returns to normal.

**Comment by Blu3wolf** [comment]
Okay, lets put that in a new issue as its a separate problem.
