### ISSUE TITLE
Treefarm is lost when placed in an invalid location

### ISSUE THREAD

**Issue by StephenWard** [Blu3wolf/Treefarm-Lite#37]
Originally #30 - don't know how to reopen and haven't verified that #30 isn't happening

> In Treefarm Lite version 0.4.0, when you place a tree farm (MK1) in an invalid location, you no longer get the error message (as in previous versions), instead it just disappears and is lost. You don't get the item back.

**Comment by Blu3wolf** [comment]
To clarify - you can confirm this is happening? At the least perhaps lets add the error message back.

**Comment by secondadvent** [comment]
Think I said this the last time this popped up, but the item isn't lost just dropped on the ground around where the chest would appear (kinda hard to see it as an item on dirt, but should be more visible elsewhere). The dropping happens when there's an entity in the "field" area that would stop normal placement of stuff (though oddly ore seems to be included in what forces it to drop, at least with my mods), though the only "invalid" placement locations that it shows you are where the chest can't be placed. You can place the same stuff on the field area after it's placed; it only fails the placement of the field initially.

It is still happening for me on 0.4.1 so it's most definitely still around.

EDIT: Another random thing I recall blocking the field placement is tree stumps - this is what was originally stopping my farms from being placed and lead me to believe ground clutter stopped them as well. I've since just used the farms to instantly clear the trees for free when making space for some farms so there's no stumps. They happily plop down when trees are in the road, but fail on pretty much anything else :P

**Comment by StephenWard** [comment]
Fixed in pull request #43
