### ISSUE TITLE
Tree-Farm Lite Dependencies base >= 0.12.12

### ISSUE THREAD

**Issue by Kamakaziee** [Blu3wolf/Treefarm-Lite#46]
I am running Factorio verson 12.3 and I cant seem to get treefarm lite to work. It seems the 0.12.12 base dependency is missing? How do I go about fixing this? 

See image below.

![image](https://cloud.githubusercontent.com/assets/19628074/15630180/f12bf660-24e3-11e6-86dc-035318aedab4.png)

**Comment by Blu3wolf** [comment]
Update your factorio version. There is an automatic updater built into it and if you use the steam version, there is an automatic updater built into steam. 

Treefarm-Lite is not compatible with such an old version of Factorio, due to changes made in Factorio version 0.12.12, so you will have to update at least to that version. 0.12.34 is out, and I would recommend updating to that.

**Comment by Kamakaziee** [comment]
Thanks for the prompt response! But I believe I have factorio version 12.3, that's what it says when I click about in my factorio client.

**Comment by Blu3wolf** [comment]
And that is the problem. Factorio 0.12.3 is too old to work with the current version of Treefarm-Lite. You will either have to update your Factorio to at least version 0.12.12 (ideally to 0.12.34) or use an older version of Treefarm-Lite.

**Comment by secondadvent** [comment]
I'm guessing you think 0.12.3 is 0.12.30, but it's actually "0.12.03" instead. "03" is lower than 12 which is why it doesn't satisfy the >= 0.12.12 dependency. You'll also likely run into plenty of other mod problems if you thought your version was 0.12.30 :P

**Comment by StephenWard** [comment]
what info is needed @Blu3wolf ?

**Comment by Blu3wolf** [comment]
just which version the user has. Given the lack of replies on it though, Im happy to close this one and let another issue be opened if the issue persists.
