### ISSUE TITLE
Thoughts on field efficiency

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#53]
So the Mk2 fields auto plant, but need robots to harvest. The Mk1 fields auto plant and harvest. On the whole, the Mk1 fields sound more efficient - the larger size of the Mk2 fields notwithstanding. 

Thoughts on making the Mk1 fields smaller? Perhaps 6x6, or 6x7, instead of the current 7x8?

Alternatively, other thoughts on how there could be a bigger difference made between the Mk1 and Mk2 fields?

**Comment by StephenWard** [comment]
I think the fields are distinguished fine as they are. The mk2 supports about 400 trees and the mk1 about half that. In addition, the mk1 requires a chest for each input (seeds, fertilizer), is a pain to feed fertilizer to, and needs long belts to retrieve the output. If a field needs to be nerfed, it's the mk2.

You'll start planting w/ mk1s, but once you can produce at scale you'll switch to mk2s, since robots are really rather cheap, and we've fixed the performance problem.

**Comment by Blu3wolf** [comment]
The mk1 supports about an eighth as many as 400, 7x8. The mk2 looks at a glance like 400, 20×20, but there is a gap in the middle - the tower - where you cant plant. Although the planting function does try, Ive noticed. Thats something that I might do some tests on changing, having it skip the tower for planting.

**Comment by StephenWard** [comment]
the tower accounts for 4 trees and costs 4 seconds of planting time. eh.

**Comment by Blu3wolf** [comment]
It was more something I thought interesting, rather than necessary.

You make a good point RE the belts.

**Comment by Blu3wolf** [comment]
Completely unrelated to the above, but I couldnt be bothered creating an Issue for this.

http://www.somsubhra.com/github-release-stats/?username=Blu3wolf&repository=Treefarm-Lite

Cool tool for seeing downloads of GitHub releases! We have had a lot more downloads than I thought.

**Comment by Blu3wolf** [comment]
Can add another hundred or so onto that figure, as well, from https://mods.factorio.com/mods/Blu3wolf/Treefarm-Lite as it mirrors the file, rather than links it. Shame that. Maybe a feature update for later.
